# Generated by Django 5.2.4 on 2025-08-06 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('csr', models.FileField(upload_to='csrs/')),
                ('dns_token', models.CharField(default='fe69c8a1548c40eaa0bae8d99a11b56f', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending DNS Validation'), ('valid', 'Validated'), ('rejected', 'Rejected'), ('issued', 'Certificate Issued')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
