# Generated by Django 5.1.3 on 2025-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caCode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificaterequest",
            name="dns_token",
            field=models.CharField(
                default="242bbecc8c4f4c1ab6757b30c91f2862", max_length=64
            ),
        ),
    ]
