# Generated by Django 5.2.4 on 2025-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0002_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='f2baad8536424739b383092ac51f0a7b', max_length=64),
        ),
    ]
