# Generated by Django 5.2.4 on 2025-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0003_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='b7b60433ad854c74b8c4388d04b912b2', max_length=64),
        ),
    ]
