# Generated by Django 5.2.4 on 2025-08-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0004_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='067880160a664ac1ac0201260c922ec5', max_length=64),
        ),
    ]
