# Generated by Django 5.2.4 on 2025-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0005_certificaterequest_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='2eb3fdafa1a043e99554c604ad169554', max_length=64),
        ),
    ]
