# Generated by Django 5.2.4 on 2025-08-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0006_certificaterequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='0cba3801d49144a7b1173374b0b74b4b', max_length=64),
        ),
    ]
