# Generated by Django 5.2.4 on 2025-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0007_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='7ee4374facba4d9380384300c994b556', max_length=64),
        ),
    ]
