# Generated by Django 5.2.4 on 2025-08-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0008_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default='523e990e9e344e1da7f571432adb4ce4', max_length=64),
        ),
    ]
