# Generated by Django 6.0.5 on 2026-06-01 00:06

import caCode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0009_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='dns_token',
            field=models.CharField(default=caCode.models.get_uuid_hex, max_length=64),
        ),
    ]
