# Generated by Django 6.0.5 on 2026-06-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0010_alter_certificaterequest_dns_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
