# Generated by Django 6.0.5 on 2026-06-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0011_certificaterequest_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending DNS Validation'), ('valid', 'Validated'), ('rejected', 'Rejected'), ('issued', 'Certificate Issued'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
