# Generated by Django 6.0.5 on 2026-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caCode', '0012_certificaterequest_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRLState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_crl_number', models.BigIntegerField(default=1)),
                ('last_generated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='revocation_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
